os: linux
dist: xenial
language: python
python: '3.7'
cache:
- directories:
  - "$HOME/.npm"
- pip
services:
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
jobs:
  include:
  - stage: test
    exclude:
      - if: branch = sandbox
    install:
    - pip install -r requirements.txt
    - cd frontend
    - npm ci && cd ..
    before_script:
    - psql -c "create user invisible_flow;"
    - psql -c "create database invisible_flow_testing with owner invisible_flow;"
    - psql invisible_flow_testing -c "CREATE EXTENSION postgis;"
    - export ENVIRONMENT=travis
    script:
    - flake8 .
    - mypy invisible_flow
    - pytest --cov=invisible_flow tests --cov-fail-under 70
    - python run-api-tests.py
    - cd frontend
    - npm run test && cd ..
  - stage: Heroku_deploy_sandbox
    if: branch = sandbox
    before_deploy: cd frontend && npm ci && npm run build && cd ..
    deploy:
      provider: heroku
      api_key:
        secure: onbG3IKjk1B3uX0Foqw6nIAtcMNBo+cmDL8467LmdsojZ/3L3ZLe7iIPnmLlQT2/CBMRG0w//TeC8HSu63xmIzYngNdVq4EvzZ28rY5zDk3Ib4XU0xDMPeo2P8a4VRzFS2ztOZ6Wh7F+9iwzb+7dy0IBLnEaQGG0GZQ0ZCrCh3lb2CJ9/TPepzuSzMzTgW1I7/oF5Z0lziU22sYCl/bhLrL3GVtv7p3/PDD9C30aOcsV2ubT+HXciEREBg7G/0c7Zdc7EkxPGtua11pwu1XFXwhtd9rkPrpRFPfMgLEMmWvbCo/c9G/mG/nynkRCYZzWlz8F27QP9MjwrV4VVMuw+gdT2uNDLPZWzICiAdV2SL6TLFsKTI6knt5adUhweHQhamnm0PrZp45JtksroXOtVG4VLUxtoRsOuLkZD6is5bGfQ1IvP/hELMDjI/cW98T/LwDXeNtxYabkNJ/F1X+GJ/TlAQMHwHqaqdotmerTqKSuLUbWI42ofpgzpmvkaKsgFmujeU9JKF1TGb7jOYvmZD6SoPNqa3ZnCzFQHVBth5qSU/o8vaDPixMTAR10yx6Pf48cfo+ube3GY5kGmKhOI1LcigYmwykBLNBVtEUh8meqzJoEC8K99E1K5vL4fUckh/Xnju11S7bTuIeWC6MMaJwwb7Pr4/EbvxkkTc4N/vs=
      app: invisiflow-sb
      on:
        repo: invinst/invisible-flow
        branch: sandbox
      skip_cleanup: true
    script: skip
  - stage: Heroku_deploy_testing
    if: branch = master
    before_deploy: cd frontend && npm ci && npm run build && cd ..
    deploy:
      provider: heroku
      api_key:
        secure: onbG3IKjk1B3uX0Foqw6nIAtcMNBo+cmDL8467LmdsojZ/3L3ZLe7iIPnmLlQT2/CBMRG0w//TeC8HSu63xmIzYngNdVq4EvzZ28rY5zDk3Ib4XU0xDMPeo2P8a4VRzFS2ztOZ6Wh7F+9iwzb+7dy0IBLnEaQGG0GZQ0ZCrCh3lb2CJ9/TPepzuSzMzTgW1I7/oF5Z0lziU22sYCl/bhLrL3GVtv7p3/PDD9C30aOcsV2ubT+HXciEREBg7G/0c7Zdc7EkxPGtua11pwu1XFXwhtd9rkPrpRFPfMgLEMmWvbCo/c9G/mG/nynkRCYZzWlz8F27QP9MjwrV4VVMuw+gdT2uNDLPZWzICiAdV2SL6TLFsKTI6knt5adUhweHQhamnm0PrZp45JtksroXOtVG4VLUxtoRsOuLkZD6is5bGfQ1IvP/hELMDjI/cW98T/LwDXeNtxYabkNJ/F1X+GJ/TlAQMHwHqaqdotmerTqKSuLUbWI42ofpgzpmvkaKsgFmujeU9JKF1TGb7jOYvmZD6SoPNqa3ZnCzFQHVBth5qSU/o8vaDPixMTAR10yx6Pf48cfo+ube3GY5kGmKhOI1LcigYmwykBLNBVtEUh8meqzJoEC8K99E1K5vL4fUckh/Xnju11S7bTuIeWC6MMaJwwb7Pr4/EbvxkkTc4N/vs=
      app: invisiflow-testing
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    script: skip
  - stage: Heroku_deploy_staging
    if: branch = staging
    before_deploy: cd frontend && npm ci && npm run build && cd ..
    deploy:
      provider: heroku
      api_key:
        secure: onbG3IKjk1B3uX0Foqw6nIAtcMNBo+cmDL8467LmdsojZ/3L3ZLe7iIPnmLlQT2/CBMRG0w//TeC8HSu63xmIzYngNdVq4EvzZ28rY5zDk3Ib4XU0xDMPeo2P8a4VRzFS2ztOZ6Wh7F+9iwzb+7dy0IBLnEaQGG0GZQ0ZCrCh3lb2CJ9/TPepzuSzMzTgW1I7/oF5Z0lziU22sYCl/bhLrL3GVtv7p3/PDD9C30aOcsV2ubT+HXciEREBg7G/0c7Zdc7EkxPGtua11pwu1XFXwhtd9rkPrpRFPfMgLEMmWvbCo/c9G/mG/nynkRCYZzWlz8F27QP9MjwrV4VVMuw+gdT2uNDLPZWzICiAdV2SL6TLFsKTI6knt5adUhweHQhamnm0PrZp45JtksroXOtVG4VLUxtoRsOuLkZD6is5bGfQ1IvP/hELMDjI/cW98T/LwDXeNtxYabkNJ/F1X+GJ/TlAQMHwHqaqdotmerTqKSuLUbWI42ofpgzpmvkaKsgFmujeU9JKF1TGb7jOYvmZD6SoPNqa3ZnCzFQHVBth5qSU/o8vaDPixMTAR10yx6Pf48cfo+ube3GY5kGmKhOI1LcigYmwykBLNBVtEUh8meqzJoEC8K99E1K5vL4fUckh/Xnju11S7bTuIeWC6MMaJwwb7Pr4/EbvxkkTc4N/vs=
      app: invisiflow-staging
      on:
        repo: invinst/invisible-flow
        branch: staging
      skip_cleanup: true
    script: skip
env:
  global:
    secure: QtSkwjcslKJ7LyjP0cLuiIBbL6P+aii0xN+2sk2YS3IK4jDVyagyPcDmXAGml7uqXZjgSj6TBoJP8t51S9OJSG4HZhfcG5cj62q/RiglONSQzqHKOCaBfEypd8Nrtkx31MMQLmpJuIHrZtQUhHN1vBYDzdo0Iti/5CukgSqb67RuxL1aGmXkUkAJwd8JTmgH85dfZ+E5sD4Ns3LU3F5IQqk7gJ/y9gLMmV8wiUWStBwTeQCV8Kp9qVMFUonHAB5OzEuYRaasYr05XlcyByxWOJPhcPHEkXs1KGobhjph07UxZ49ORzrvtj6Go0hDLkti5Nenpltc1w4nrXg7AsNC4eACZ0WzSTmqXJ5g9UPzUgElxj1bnfqQSokL9Fxq/rZc3nObbnfdimSRXqbs8MOXPlyLM3CEU3kpkm6zAybZEXGBqAE763EJy9FNVptz4rdU0PDpwuCwi1e2QwXZhu8xc/Y93p5fT5QJqT4RL0hhv5S54XmSXH9YPx+7vxZcRbCeOi0UVg0CDer1gtImGZCiPwer8BvqP8RCcSYzQIJ4mhI764HpIOnFI4kgn9VAxnIe6HZCTZM88vc9znmk4Am/+HEnivhDoSOW6XFnvcUz3N81pX28zdIG9l8EsMvV7Ls+cVeNhiRcRCovI2XQqiwlS9tj8IxiuEt9sJXuSE/c3K0=
